// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using st10275468_PROG6212_POE_ThomasK_gr03.Data;

#nullable disable

namespace st10275468_PROG6212_POE_ThomasK_gr03.Migrations
{
    [DbContext(typeof(ContractManagementContext))]
    [Migration("20241014125028_UpdateClass2")]
    partial class UpdateClass2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("st10275468_PROG6212_POE_ThomasK_gr03.Models.Claim", b =>
                {
                    b.Property<int>("claimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("claimID"));

                    b.Property<decimal>("claimAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("claimMonth")
                        .HasColumnType("datetime2");

                    b.Property<string>("claimStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("submissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("claimID");

                    b.HasIndex("userID");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("st10275468_PROG6212_POE_ThomasK_gr03.Models.Document", b =>
                {
                    b.Property<int>("documentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("documentID"));

                    b.Property<int>("claimID")
                        .HasColumnType("int");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("documentID");

                    b.HasIndex("claimID");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("st10275468_PROG6212_POE_ThomasK_gr03.Models.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userID"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("st10275468_PROG6212_POE_ThomasK_gr03.Models.Claim", b =>
                {
                    b.HasOne("st10275468_PROG6212_POE_ThomasK_gr03.Models.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("st10275468_PROG6212_POE_ThomasK_gr03.Models.Document", b =>
                {
                    b.HasOne("st10275468_PROG6212_POE_ThomasK_gr03.Models.Claim", "Claim")
                        .WithMany("Documents")
                        .HasForeignKey("claimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("st10275468_PROG6212_POE_ThomasK_gr03.Models.Claim", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("st10275468_PROG6212_POE_ThomasK_gr03.Models.User", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
